name: theme_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # display photos in grid
  flutter_staggered_grid_view: ^0.3.3
  ff_annotation_route_library: 3.0.0
  pull_to_refresh_notification: any
  extended_sliver: ^2.0.1

  # state management
  provider: ^4.3.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/